# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 rtime-assistant contributors (see NOTICE)
"""Render a settings model's JSON Schema into a stable Markdown reference.

One function, ``schema_to_markdown``, turns ``Model.model_json_schema()`` into a
deterministic table (field / env name(s) / type / default / secret / reload /
description). "Deterministic" is load-bearing: the output is golden-tested, so a
schema change (added field, changed default, renamed alias) shows up as a diff
that a human must review before it lands (docs/development-plan.zh-CN.md §五 L0).

The table is derived purely from the schema dict, so it also works for any model
that carries the rtime ``x-secret`` / ``x-reload`` metadata — not just
QQBridge — which is what makes it reusable across the whole config rollout.
"""

from __future__ import annotations

import json
from typing import Any


def _env_names(prop: dict[str, Any], field_name: str, env_prefix: str) -> list[str]:
    """The env var name(s) that populate this field, in resolution order.

    pydantic serialises a ``validation_alias`` into the schema differently
    depending on whether it is a plain string or an ``AliasChoices``. We surface
    whatever is there; if nothing, fall back to ``<PREFIX><FIELD>`` upper-cased,
    which is exactly what pydantic-settings uses for a prefixed field with no
    explicit alias.
    """
    # pydantic dumps AliasChoices under one of these keys depending on version.
    alias = prop.get("x-env-aliases")
    if alias:
        return list(alias)
    return [f"{env_prefix}{field_name}".upper()]


def _fmt_default(prop: dict[str, Any]) -> str:
    if "default" not in prop:
        # A default_factory value is stashed under x-default by config_field.
        if "x-default" in prop:
            default = prop["x-default"]
        else:
            return "*(required)*"
    else:
        default = prop["default"]
    if default is None:
        return "`null`"
    if default == "":
        return '`""` (empty)'
    if isinstance(default, bool):
        return f"`{str(default).lower()}`"
    if isinstance(default, (list, tuple, set, frozenset)):
        if not default:
            return "`[]` (empty)"
        return "`" + json.dumps(sorted(map(str, default)), ensure_ascii=False) + "`"
    if isinstance(default, (dict,)):
        return "`" + json.dumps(default, ensure_ascii=False, sort_keys=True) + "`"
    return f"`{default}`"


def _fmt_type(prop: dict[str, Any]) -> str:
    if "type" in prop:
        t = prop["type"]
        if t == "array":
            items = prop.get("items", {})
            it = items.get("type", "any") if isinstance(items, dict) else "any"
            return f"array<{it}>"
        return str(t)
    if "anyOf" in prop:
        parts = []
        for sub in prop["anyOf"]:
            if sub.get("type") == "null":
                parts.append("null")
            elif "type" in sub:
                parts.append(str(sub["type"]))
            else:
                parts.append("any")
        return " | ".join(parts)
    return "any"


def _escape(text: str) -> str:
    """Make a description safe for one Markdown table cell (single line)."""
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def schema_to_markdown(
    schema: dict[str, Any],
    *,
    title: str,
    env_prefix: str = "",
    intro: str = "",
) -> str:
    """Return a Markdown document describing every field in ``schema``.

    ``schema`` is the dict from ``Model.model_json_schema()``. ``env_prefix`` is
    only used to synthesise the env name for fields without an explicit alias.
    """
    props: dict[str, Any] = schema.get("properties", {})
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append(
        "<!-- GENERATED by rtime_config.schema_to_markdown — do not edit by hand. "
        "Regenerate: python -m rtime_config <module:Model> and review the diff. -->"
    )
    lines.append("")
    if intro:
        lines.append(intro.strip())
        lines.append("")
    lines.append("| 字段 | env 名 | 类型 | 默认值 | 秘密 | 生效 | 说明 |")
    lines.append("|---|---|---|---|---|---|---|")
    for name in props:  # dict preserves field declaration order
        prop = props[name]
        env = ", ".join(f"`{e}`" for e in _env_names(prop, name, env_prefix))
        typ = _fmt_type(prop)
        default = _fmt_default(prop)
        secret = "是" if prop.get("x-secret") else ""
        reload = prop.get("x-reload", "")
        desc = _escape(prop.get("description", ""))
        lines.append(
            f"| `{name}` | {env} | {typ} | {default} | {secret} | {reload} | {desc} |"
        )
    lines.append("")
    return "\n".join(lines)
