# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 rtime-assistant contributors (see NOTICE)
"""Unit tests for the rtime-config foundation (base + fields + schema_doc)."""

from __future__ import annotations

from pydantic_settings import SettingsConfigDict
from rtime_config import (
    RtimeBaseSettings,
    config_field,
    schema_to_markdown,
    secret_field,
)
from rtime_config.fields import Reload


class Sample(RtimeBaseSettings):
    model_config = SettingsConfigDict(env_prefix="")
    name: str = config_field("anon", description="a name", env_aliases=["APP_NAME"])
    port: int = config_field(80, description="a port", reload=Reload.HOT)
    token: str | None = secret_field(
        None, description="a secret", env_aliases=["APP_TOKEN"]
    )


def test_env_alias_loads(monkeypatch):
    monkeypatch.setenv("APP_NAME", "prod")
    monkeypatch.setenv("APP_TOKEN", "sk-1")
    s = Sample()
    assert s.name == "prod"
    assert s.token == "sk-1"


def test_direct_kwargs_win_over_env(monkeypatch):
    monkeypatch.setenv("APP_NAME", "from-env")
    assert Sample(name="explicit").name == "explicit"


def test_metadata_in_schema():
    schema = Sample.model_json_schema(by_alias=False)
    props = schema["properties"]
    assert props["token"]["x-secret"] is True
    assert props["port"]["x-reload"] == "hot"
    assert props["name"]["x-reload"] == "restart"  # default
    assert props["name"]["x-env-aliases"] == ["APP_NAME"]
    # non-secret fields carry no x-secret key
    assert "x-secret" not in props["name"]


def test_extra_env_ignored(monkeypatch):
    monkeypatch.setenv("SOMETHING_UNRELATED", "x")
    Sample()  # must not raise


def test_env_aliases_and_validation_alias_conflict():
    import pytest
    from pydantic import AliasChoices

    with pytest.raises(ValueError):
        config_field(
            "x",
            description="bad",
            env_aliases=["A"],
            validation_alias=AliasChoices("B"),
        )


def test_schema_to_markdown_shape():
    schema = Sample.model_json_schema(by_alias=False)
    md = schema_to_markdown(schema, title="Sample cfg", env_prefix="")
    assert md.startswith("# Sample cfg")
    assert "GENERATED by rtime_config.schema_to_markdown" in md
    # header row + each field row
    assert "| 字段 | env 名 | 类型 | 默认值 | 秘密 | 生效 | 说明 |" in md
    assert "`name`" in md and "`APP_NAME`" in md
    assert "`token`" in md
    # secret field marked 是
    token_row = next(line for line in md.splitlines() if "`token`" in line)
    assert "是" in token_row
    # description pipe-escaping keeps the table one column per field
    assert md.count("\n") >= 5


def test_schema_to_markdown_is_deterministic():
    schema = Sample.model_json_schema(by_alias=False)
    a = schema_to_markdown(schema, title="X")
    b = schema_to_markdown(schema, title="X")
    assert a == b
